### ISSUE TITLE
CreateLink

### ISSUE THREAD

**Issue by ivanov84** [piedoom/TumblrSharp#15]
Hello.
When I use this method - thumbnail does not appear.
But when I put it manually via dashboard - it appeared.
Could you help me to make something so thumbnail appears?

**Comment by ivanov84** [comment]
Solved.
I have added code (attached image) and after rebuild it's work well =)

![2017-06-30_01-35-31](https://user-images.githubusercontent.com/9296077/27713492-a650fb9c-5d34-11e7-832a-fe48e1abe2e0.png)

**Comment by piedoom** [comment]
Glad to hear you got it working!  Let me know if you run into any other issues.

**Comment by 8VAid8** [comment]
> Solved. I have added code (attached image) and after rebuild it's work well =)
> 
> ![2017-06-30_01-35-31](https://user-images.githubusercontent.com/9296077/27713492-a650fb9c-5d34-11e7-832a-fe48e1abe2e0.png)

Thanks for a hint. I resolved the issue in other way:

```
private async Task SendLinkToTumblr(string url, string title, string thumbnail, string excerpt, List<string> tags)
{
    Console.WriteLine("Posting to Tumblr...");
    var post = PostData.CreateLink(url, title, tags: tags);
    var extPost = post.ToMethodParameterSet();
    extPost.Add("thumbnail", thumbnail);
    extPost.Add("excerpt", excerpt);

    try
    {
        await tumblrClient.CallApiMethodAsync<PostCreationInfo>(new BlogMethod(blogName, "post", new DontPanic.TumblrSharp.OAuth.Token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET), HttpMethod.Post, extPost), CancellationToken.None);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
}
```
