### ISSUE TITLE
No exception / error message when creating post

### ISSUE THREAD

**Issue by annvnzndrvn** [piedoom/TumblrSharp#16]
Hi,

I'm trying to create a post using below code:

`            _client.CreatePostAsync("myblog.tumblr.com", PostData.CreateText("adwqeqweasd"));
`

Here's the client set up:

`            CONSUMER_KEY = "xxx";
            CONSUMER_SECRET = "xxx";
            OAUTH_TOKEN = "xxx";
            OAUTH_TOKEN_SECRET = "xxx";`
` _client = new TumblrClientFactory().Create<TumblrClient>(CONSUMER_KEY, CONSUMER_SECRET, 
                new DontPanic.TumblrSharp.OAuth.Token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET));`

I'm not sure if the format of the blog string is correct. I tried using "myblog". "myblog.tumblr.com" and "https://myblog.tumblr.com/". There are no error messages at all and OAuthToken.IsValid inside _client is 'true'. The blog I'm targetting is the only primary blog in my account. Leaving a blank string does trigger error message "Blog name cannot be empty" but other than that, there are no error messages which might explain what could be going wrong here. I would say auth seems OK. 

Should I use the email and password somewhere or is it not needed after specifying the four secret keys?

**Comment by piedoom** [comment]
You should be using `myblog` and not `myblog.tumblr.com`.  Being said, that should have worked.   You never need to use your email or password.

When you created your API keys, were they on the same account as the `myblog` that you are posting to?  If they are not owned by the same user, you will either need to get keys from the account you intend to post with, or implement some sort of [oauth flow](https://github.com/piedoom/TumblrSharp/wiki/Authenticating) (especially if you intend to release the app to other people).

If this isn't the case, let me know and I'll look further into the issue.

**Comment by annvnzndrvn** [comment]
The app is just for my own use, that's why I didn't implement the oauth flow. This is the only Tumblr account I have and it only has one blog. When going through the process of getting the token and secret it does ask me if I'd like to authorize myapp name to access myblog and I do receive an email stating that the access has been granted.

However, I did notice that every time I log out and log in to the API tumblr console, both the token and token secret change (I'm not sure if this is the correct behavior). I also tried changing them in my code to reflect the most current token and secret but no luck.

Is there any way to catch the response to check for success/failure when calling CreatePostAsync?

**Comment by piedoom** [comment]
As far as the token/secret changing, that is correct behavior.  You are granted a new token every time you log in to the console with your consumer keys.  I get around this by creating a Tumblr oauth application specifically for using the API console, so I never need to change my app's OAuth tokens.  

As far as catching success/failure, if an error occurred it should be displayed to the console.  However, it's very possible that something is wonky with authentication error checking, and that's something I'll have to check.  

In the meantime, I can take a look at the offending code (of course with the tokens redacted) if you'd like to do so.  I might be able to determine what the underlying issue is.

**Comment by annvnzndrvn** [comment]
The application runs fine without stopping at any point or showing any error message. At first I thought maybe it takes some time for the post to be available on Tumblr itself, but it's clearly not the case.

Here's the file (I only changed the extension to .txt and redacted the keys).

[TumblrPoster - Copy.txt](https://github.com/piedoom/TumblrSharp/files/1117291/TumblrPoster.-.Copy.txt)

I'll try using tumblr.js library and see if it posts the stuff fine (that should rule out issues with the authorization) but I really prefer using C# and your library looks very nice :)

**Comment by Cataurus** [comment]
Here is a solution:

```C
using DontPanic.TumblrSharp;
using DontPanic.TumblrSharp.OAuth;
using DontPanic.TumblrSharp.Client;
using System;
using System.Threading.Tasks;

namespace Test
{
    public class tumblr
    {
        private TumblrClient client = null;

        private string CONSUMER_KEY = "xxx";
        private string CONSUMER_SECRET = "xxx";
        private string OAUTH_TOKEN = "xxx";
        private string OAUTH_TOKEN_SECRET = "xxx";

        public tumblr()
        {
            this.client = new TumblrClientFactory().Create<TumblrClient>(CONSUMER_KEY, CONSUMER_SECRET, new Token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET));
        }

        public async Task<PostCreationInfo> Post()
        {
           // important CreatePostAsync is a asynchrony method 
            var test = await client.CreatePostAsync("BlogName", PostData.CreateText("adwqeqweasd")).ConfigureAwait(false);

            return test;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            tumblr tb = new tumblr();

            Console.WriteLine("Posted Text");
            Console.WriteLine();

           // Important wait for result
            var test = tb.Post().GetAwaiter().GetResult();

            Console.WriteLine("Post ID: " + test.PostId.ToString());

            Console.ReadKey();
        }
    }
}
```
