### ISSUE TITLE
exeptionservicecommon.cs  not found

### ISSUE THREAD

**Issue by softmarshmallow** [piedoom/TumblrSharp#19]
is this not compatible with mac? mono

**Comment by piedoom** [comment]
It should be.  However, I do no have access to a Mac so I unfortunately cannot test for it at the moment.  Could you explain the title of this issue in more depth?  I don't understand the issue.

**Comment by Cataurus** [comment]
With the addition of .Netstandard 1.3 support, Mono 4.6 and higher is also supported. 
We'd like you to test this one.
