### ISSUE TITLE
windows 10UAP compatiblity

### ISSUE THREAD

**Issue by jkw117** [piedoom/TumblrSharp#20]
I've used Tumblr# the original with windows 8, as a windows store app. 
Now I'm trying to fix/rebuild it for UAP10 (windows 10 store) and basically can't get it to even let me add it into my project. I get a combination of newtumblrsharp isn't compatible as well as PCL and a bunch of other ones.
Is there a workaround, am I being an idiot? Is there a new guide? with a little more direction that may enlighten me? Or is it just not compatible and it was a miracle I got it to work in 8? LOL

**Comment by piedoom** [comment]
This is definitely something on my end.  I think the assemblies are perfectly compatible but NuGet is not set up correctly, which is something I'll have to figure out.  In the meantime, if you clone the repo and reference it locally it should work. 

This would probably work if we added [`uap` to the nuspec](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks).  I thought that a regular net45 PCL would be compatible with anything, but that must not be the case.

**Comment by jkw117** [comment]
Thanks ill give it a try.. I'll clone it locally, then add it to my solution. Or maybe compile it separately and then reference it in.. I guess ill have to see how it works out.. Programming is a hobby for me,not my living So I'm far from an expert... Lol its a miracle i ever got my app initially in the store

**Comment by piedoom** [comment]
Great, let me know how that goes.  Thanks for bringing the issue up regardless as it needs to be fixed eventually.

**Comment by Cataurus** [comment]
Fixed by last merged
