### ISSUE TITLE
FollowAsync and UnfollowAsync returns bad request/not found

### ISSUE THREAD

**Issue by Dominik-cmd** [piedoom/TumblrSharp#21]
I'm running my code as 
`await Tumblr.Client.UnfollowAsync("stupid.tumblr.com");`

I've also tried with "https://stupid.tumblr.com/", and just "stupid". All return not found, if I do it with the follow method, everything returns "bad request". Any help? Thanks.

**Comment by Cataurus** [comment]
You must in tumblrclient.cs  change the **HttpMethod** from **Get** to **Post** for the method

```C#
public Task UnfollowAsync(string blogUrl)
{
.
.
.
	return CallApiMethodNoResultAsync(
			new UserMethod("unfollow", OAuthToken, HttpMethod.Post, parameters),
			CancellationToken.None);
}
```
and

```C#
public Task FollowAsync(string blogUrl)
{
.
.
.
	return CallApiMethodNoResultAsync(
			new UserMethod("follow", OAuthToken, HttpMethod.Post, parameters),
			CancellationToken.None);
}
```

**Comment by Dominik-cmd** [comment]
Why is the method set to Get? This fixes the issue, thank you!

**Comment by piedoom** [comment]
This is an issue with the library, so I'm going to reopen this.  Thanks for the spot, Cataurus.
