### ISSUE TITLE
How to use CallApiMethodAsync<> ?

### ISSUE THREAD

**Issue by GeHertz** [piedoom/TumblrSharp#29]
Hi,

I want to extract few information from user post, how can i achieve that with CallApiMethodAsync?
I don't really understand about the converter argument,

`await Client.CallApiMethodAsync(postMethod, CancellationToken, converters);`

> converters =  an optional list of JSON converters that will be used while deserializing the response from the tumblr api

Can you give me an example?

**Comment by Cataurus** [comment]
In the file TumblrClient.cs, look at the GetTaggedPostAsync method. There you will find an example.
