### ISSUE TITLE
I am not quite understanding the Authenticating guide

### ISSUE THREAD

**Issue by teenangst** [piedoom/TumblrSharp#30]
I have not done OAuth before and am a little confused with the bottom of [/wiki/Authenticating](https://github.com/piedoom/TumblrSharp/wiki/Authenticating)
```
// this will look different depending on what your platform uses to open URI schemes
[SomeFlagThatTellsThisMethodWhatToOpen]
```
I am just trying to make a private bot which will run on a server - so first I don't want a browser window to open and second I don't need a flexible solution, I just want it to verify and skip the security.

**Comment by piedoom** [comment]
In that case, just follow the "Authenticating without OAuth Flow" section.  This lets you directly input your consumer & token keys without needing the full OAuth 1.0a flow.  You can ignore the rest of the page.

**Comment by teenangst** [comment]
Oh, I'm not sure how I missed that 😬
