### ISSUE TITLE
Queuing for image posts don't work

### ISSUE THREAD

**Issue by teenangst** [piedoom/TumblrSharp#32]
I am able to queue other forms

- [x] Text
- [x] Chat
- [x] Link
- [x] Quote

(Have not tried answers, audio, or video)

I am using this to try to queue:
```C
await Tumblr.CreatePostAsync(
        "my blog", 
        PostData.CreatePhoto(
            new BinaryFile(
                ImageToByteArray(@"file location")
            ), 
            null, 
            new List<string> { "tag" }, 
            PostCreationState.Queue
        )
    );
```

The image is posted directly and not being queued (it's not being queued and automatically posted as it isn't meant to post and isn't happening to other submissions) so I don't think it's an issue with the above, I do not have any issues with text using `PostCreationState.Queue` and I am able to post an image to the queue so I don't see it being a tumblr issue.

**Comment by Cataurus** [comment]
I've tested it with following:
```C
MemoryStream arrayStream = new MemoryStream();

using (var stream = new FileStream(@"file location", FileMode.Open))
{
    stream.CopyTo(arrayStream);
}

byte[] array = arrayStream.ToArray();

PostData postData = PostData.CreatePhoto(new BinaryFile(array), null, new List<string>(), PostCreationState.Queue);

await tumblrClient.CreatePostAsync(blogName, postData);
```
It works correctly. You can view the queue using the "GetQueuedPostsAsync" method.

**Comment by teenangst** [comment]
I tried your method and it's the same output, it posts directly and skips the queue @ https://www.tumblr.com/blog/_my-blog_/queue

**Comment by teenangst** [comment]
The issue is present with the normal queue and queue 2.0 (and not present with other post types stated in the initial post)

**Comment by Cataurus** [comment]
This is the [Fotopost-Demo](https://github.com/piedoom/TumblrSharp/tree/cataurus/Examples/Windows/Forms/Post_Photo_Queue) project I used for the tests. The test was successful. The post was displayed in the queue. (https://www.tumblr.com/blog/_my-blog_/queue) Please test this project directly.

**Comment by teenangst** [comment]
I'll get on that tomorrow morning 👍
