### ISSUE TITLE
nuget package version

### ISSUE THREAD

**Issue by Cataurus** [piedoom/TumblrSharp#35]
The latest version of package is 1.1.27. That can't be right?

**Comment by piedoom** [comment]
A new nuget package should be pushed from CI when a tagged branch is merged.  I might be incorrect in my setup though as my knowledge of NuGet is limited.  It's something to take another look at.

**Comment by piedoom** [comment]
I just realized that you've been pushing releases but the build system hasn't pushed anything to NuGet.  It's very likely a credentials error that I will check ASAP.

**Comment by Cataurus** [comment]
> Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.

**Comment by piedoom** [comment]
Sorry for my lateness on this.  Is it possible that I can add you as an administrator of the package on NuGet?  If you give me your username, I will send an invite so you can manage it.

**Comment by Cataurus** [comment]
Yes, you can do that.

**Comment by piedoom** [comment]
Done!  I added a user of the same name, hopefully that's you :)

**Comment by piedoom** [comment]
Unfortunately appveyor doesn't seem to be as easy as it should be, so I'll look into creating a team so i can give access to that.

**Comment by piedoom** [comment]
new versions are getting pushed!  yay.

https://www.nuget.org/packages/NewTumblrSharp/1.1.112
