### ISSUE TITLE
Tumblr.Client.FollowAsync Bad Request

### ISSUE THREAD

**Issue by simonfruehauf** [piedoom/TumblrSharp#36]
After trying a while, I found out that I can get almost everything to work, except for Tumblr.Client.FollowAsync() and Tumblr.Client.ReblogAsync(). 
LikeAsync works, getting posts works, and posting works too, but the line ``` await Tumblr.Client.FollowAsync("tumblrblog"); ``` gives me the error shown below.

I have tried in an async void and a non async one, and only async voids give an exception, otherwise it just passes and does nothing at all. 

```
DontPanic.TumblrSharp.TumblrException: Bad Request
   at DontPanic.TumblrSharp.TumblrClientBase.<CallApiMethodAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at tumblrsharp.Program.<Debug>d__10.MoveNext() in D:\writeblr\tumblrsharp\tumblrsharp\Program.cs:line 341
```

**Comment by Cataurus** [comment]
Do you use the Nuget packet 1.1.27?

If yes, clone the repository local and paste the two projects TumblrSharp and TumblrSharp. Client into your project.
Then the error should not occur.

Unfortunately, the Nuget package is not up to date, we are working on this problem.

**Comment by simonfruehauf** [comment]
I am using the Nuget packet, yes. 

I downloaded the project, but which files exactly do I have to paste where?

**Comment by Cataurus** [comment]
You add two projects to your solution:

- TumblrSharp.csproj

- TumblrSharp.Client.csproj

**Comment by simonfruehauf** [comment]
I can't really get that to work... I tried adding both files directly to my solution via drag and drop, and uninstalling the Nuget Package, but now i have the error "The type or namespace name 'DontPanic' could not be found (are you missing a using directive or an assembly reference?)". 

I seem to be missing the dll? Or at least the reference to it?

**Comment by Cataurus** [comment]
You need to add a reference to the two projects to your project

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/42313893-1986fe1c-8044-11e8-92dc-10f2a1edc470.png)

I get this error when trying to add a reference...

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/42314160-b8431680-8044-11e8-9bda-bbb2141f1aee.png)

And this error if i try to add the project to my solution...

**Comment by Cataurus** [comment]
Ok. Remove the two projects added and added the two projects from the portable subdirectory

**Comment by simonfruehauf** [comment]
that kind of worked? 
Apparently i'm just missing some referenced components?

![image](https://user-images.githubusercontent.com/25452923/42316490-442d45da-804a-11e8-8bf9-b4b7ec90522a.png)

**Comment by CrazyCookieBuddy** [comment]
also, i cannot use them
![image](https://user-images.githubusercontent.com/25452923/42316684-b407dc58-804a-11e8-8575-9bad76ccf41c.png)

**Comment by simonfruehauf** [comment]
I fixed the references by deleting them and re-adding them to the references, but now get another error 😢 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Google Drive\Tools\TumblrSharp-master\bin\Debug\net45\DontPanic.TumblrSharp.Client.dll' could not be found	writeblrbot	D:\Google Drive\Tools\writeblrbot\tumblrsharp\CSC	1	Active`
and
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Google Drive\Tools\TumblrSharp-master\bin\Debug\net45\DontPanic.TumblrSharp.dll' could not be found	writeblrbot	D:\Google Drive\Tools\writeblrbot\tumblrsharp\CSC	1	Active`

**Comment by simonfruehauf** [comment]
I imported the old .dll files from the older build, that apparently worked 🤷‍♂️
