### ISSUE TITLE
Is there a way to queue reblogs?

### ISSUE THREAD

**Issue by simonfruehauf** [piedoom/TumblrSharp#40]
`ReblogAsync` does not let me set a `PostCreationState` like `CreatePostAsync`, is there a way to queue the posts instead of instantly reblogging them?

**Comment by piedoom** [comment]
I don't believe queuing is available to the public API; it can only be accessed with official Tumblr API keys (which I cannot provide).

I haven't tested it but I don't see it in their API docs nor in the official Tumblr libraries.

**Comment by Cataurus** [comment]
Upgrade _ReblogAsync_ for support _PostCreationState_ and added a example
