### ISSUE TITLE
TumblrException: Unauthorized

### ISSUE THREAD

**Issue by simonfruehauf** [piedoom/TumblrSharp#41]
Upon calling `Tumblr.Client.GetFollowersAsync(Tumblr.BlogName, followerNumber, 20).Result.Result;` i get the error `System.AggregateException: 'One or more errors occurred. Inner Exception, TumblrException: Unauthorized`.
I have checked, my Keys and Tokens are up to date and correct, but the script i wrote does not post (anymore!) or interact at all with Tumblr. This is however the only error I get, and posting seems to work flawlessly - even tho no actual post gets created.

**Comment by Cataurus** [comment]
My own test environment has no problems. The information from you is not enough to reconstruct this problem.

**Comment by simonfruehauf** [comment]
What information would help?
![image](https://user-images.githubusercontent.com/25452923/45037299-87fd4a80-b056-11e8-8974-310013534f2e.png)
This is the error i mentioned, but i cannot get anything else... I have also tried on another Tumblr Account with another Key&Token, but that does not seemt o work either...


the details here:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at writeblrbot.Program.<CleanFollowers>d__24.MoveNext() in D:\GoogleDrive\Tools\writeblrbot\tumblrsharp\Program.cs:line 701

Inner Exception 1:
TumblrException: Unauthorized
```

**Comment by Cataurus** [comment]
Please post the part of the subscription to Tumblr. The error must be at this point.

**Comment by simonfruehauf** [comment]
Which part would that be? Sorry if i miss the obvious, but what snippet of code or error are you interested in?

**Comment by Cataurus** [comment]
Since the error "TumblrException: Unauthorized" indicates a faulty instantiation of the TumblrClient, this section of their code.

**Comment by simonfruehauf** [comment]
I rolled back to the code and files I used about a month ago, and the same error occurs?

Also, I have not modified the TumblrClient code, so I do not know which part could produce the error.

**Comment by CrazyCookieBuddy** [comment]
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at writeblrbot.Program.ClearInbox() in D:\GoogleDrive\Tools\writeblrbot\tumblrsharp\Program.cs:line 817
   at writeblrbot.Program.Main() in D:\GoogleDrive\Tools\writeblrbot\tumblrsharp\Program.cs:line 216

Inner Exception 1:
TumblrException: Unauthorized

```

That's all I get.

**Comment by simonfruehauf** [comment]
It still does not work, even after starting a whole new project, coding from scratch and trying to isolate the issue.

I'd be very happy to resolve the issue by providing whatever files or information you need.

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/45916307-adae9000-be5b-11e8-842e-f5c41056719e.png)

This is the complete code right now.

**Comment by Cataurus** [comment]
Your ConsumerKey has spaces at the end, this cannot be correct.

**Comment by simonfruehauf** [comment]
Oh yea, I saw. Even with that fixed however, the error still occurs.

**Comment by Cataurus** [comment]
The static field Client is not initialized in your class. The whole class construction is not correct.
Here's an example of what works:

```C
using DontPanic.TumblrSharp;
using DontPanic.TumblrSharp.Client;
using DontPanic.TumblrSharp.OAuth;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TumblrException_Unauthorized
{
    public class Tumblr
    {
        // xxx - must be replaced with the correct keys
        private string CONSUMER_KEY = "xxx";
        private string CONSUMER_SECRET = "xxx";
        private string OAUTH_TOKEN = "xxx";
        private string OAUTH_TOKEN_SECRET = "xxx";

        public TumblrClient Client { get; set; }

        public List<string> BlogNames
        {
            get
            {
                var userInfo = Client.GetUserInfoAsync().GetAwaiter().GetResult();

                List<string> result = new List<string>();

                foreach (var blog in userInfo.Blogs)
                {
                    result.Add(blog.Name);
                }

                return result;
            }
        } 

        public Tumblr()
        {
            Client = new TumblrClientFactory().Create<TumblrClient>(CONSUMER_KEY, CONSUMER_SECRET, new Token(OAUTH_TOKEN, OAUTH_TOKEN_SECRET));
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Tumblr tumblr = new Tumblr();

            var inBox = tumblr.Client.GetSubmissionPostsAsync(tumblr.BlogNames[0]).Result;

            foreach (var message in inBox)
            {
                var msg = (AnswerPost)message;

                tumblr.Client.EditPostAsync(tumblr.BlogNames[0], msg.Id, PostData.CreateAnswer("Test", null, PostCreationState.Published) );
            }

            Console.ReadLine();
        }
    }
}
```

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/45917947-2a9b3300-be77-11e8-8aa6-e5a71c261990.png)

even with that same exact code, I still get that error.

**Comment by Cataurus** [comment]
Okay, it seems to be your tokens.

1. control your consumer token with this [page](https://www.tumblr.com/oauth/apps).

2. create a new access token either with this [page](https://api.tumblr.com/console/calls/user/info) or with our [example](https://github.com/piedoom/TumblrSharp/tree/master/Examples/Windows/Authenticate1) from the repository

3. test these then please times

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/45928510-c9d62e00-bf3c-11e8-903d-2402eb1c2c79.png)
I tried creating a new access token with the application from the repo, and all i got is this error. Unauthorized.

**Comment by Cataurus** [comment]
Your ConsumerToken seems to be invalid.

**Comment by simonfruehauf** [comment]
How do i fix that then? because i tried this on several different accounts, with several different apps and users, and always get the same error

**Comment by Cataurus** [comment]
Have you ever tested your ConsumerToken with the [Api Console](https://api.tumblr.com/console/calls/user/info) from Tumblr?

**Comment by simonfruehauf** [comment]
I did, and those are the tokens i got from there.

**Comment by simonfruehauf** [comment]
![image](https://user-images.githubusercontent.com/25452923/45999172-d70a2e80-c09c-11e8-979d-a2644aebfee1.png)
even on there i get the message "unauthorized" tho...

**Comment by simonfruehauf** [comment]
It seems to be a problem of my PC, since on the same network on my Laptop, i have no trouble running the code or accessing the API

**Comment by netcrawler00** [comment]
... so the issue should be closed?
