### ISSUE TITLE
Exception on Reblogging

### ISSUE THREAD

**Issue by simonfruehauf** [piedoom/TumblrSharp#48]
Here is the exception message.
`
System.IO.FileLoadException: 'Could not load file or assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
`

**Comment by Cataurus** [comment]
To be able to reproduce this error, I would need more information. The package is intended for different platforms, for which targets do you use it?

**Comment by simonfruehauf** [comment]
I fixed the problem by reverting SshNet.Security.Cryptography back to 1.1.0.0 and then updating again. No idea what the problem was.
