### ISSUE TITLE
No error message but no post

### ISSUE THREAD

**Issue by simonfruehauf** [piedoom/TumblrSharp#49]
The application gives me no error message that the authentication failed or any other error message, and it worked a day ago with the exact same code, but now it doesn't post, like, or reblog anything anymore. 

I didn't change any code, nor are there any errors, and I tried with several different (known to be working) keys and tokens.

What could this be? Where could i start debugging?

**Comment by Cataurus** [comment]
Unfortunately I can't understand this problem with the available information. Everything works in my test environment.
