### ISSUE TITLE
source_url and source_title for posts?

### ISSUE THREAD

**Issue by SebDuf** [piedoom/TumblrSharp#5]
In the [API documentation](https://www.tumblr.com/docs/en/api/v2#posts), it shows one of the options is adding a source_url and a source_title to posts, which shows up like this:

![1](https://cloud.githubusercontent.com/assets/12822182/21560936/0dc8581e-ce34-11e6-8a0a-d2bccb5d73cf.png)

Would it be possible to add the option to include those?

Thanks!

**Comment by piedoom** [comment]
Hi!

Do you mean when creating a post, or when retrieving a post?  If you are trying to *retrieve* a source from a post, you can use the `SourceUrl` and `SourceTitle` properties.  

The [V2 API for creating a post](https://www.tumblr.com/docs/en/api/v2#posting) unfortunately does not allow for the *setting* of a source for any post type.  (Note the "Quote" and "Photo" posts have a "source" field, but *I believe* that is different than what you are referring to).  

However, in the Tumblr app, one can seemingly set the source for any type of post.  Tumblr's API reference is inaccurate to some degree, so it is worth taking a look at in MITM proxy or something similar to see if it's missing anything.

**Comment by SebDuf** [comment]
Hi!

Sorry about that, I meant when creating a post. I just re-checked the docs, and it seems like the field I had in mind is actually the source field for Quote and Photo posts (specifically for the photo posts).

**Comment by piedoom** [comment]
Let me know how it works out.   I thought the source for those particular posts meant something different (the photo source is a URL to upload from and the quote source is shown in the post, and not below like in the picture).  But I haven't tried it.
