### ISSUE TITLE
Sync methods?

### ISSUE THREAD

**Issue by FuchsiaSoft** [piedoom/TumblrSharp#54]
When doing non-interactive apps things are much simplified without having to think about the world of async and the task pattern.

`.Result` can always be used, which is what I've done before, but is there any plan to just include sync versions for consumption?

**Comment by Cataurus** [comment]
This is not intended by my side. The question of the need for support for synchronous processes arises to me. Especially with interactive applications, users don't want to wait very long for responses from internet servers that could block the interface. Perhaps you could explain your problem to me in more detail, where this is necessary.
