### ISSUE TITLE
Allow injection of HttpClient?

### ISSUE THREAD

**Issue by blackjackkent** [piedoom/TumblrSharp#55]
I run an application which makes a lot of simultaneous calls to the Tumblr API using this library and I'm running into what I think might be an issue with my hosting provider (Azure). Specifically, a percentage of the requests made are failing with the message `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

I've been doing some research and the most likely culprit I can find has to do with my application causing port exhaustion on my Azure server with all of the outbound connections (https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-intermittent-outbound-connection-errors#cause). The suggested solution to this (https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1#pool-http-connections-with-httpclientfactory) involves making use of `HttpClientFactory` to manage the generation of `HttpClient` instances to reduce the number of ports being used. Unfortunately since TumblrSharp wraps the initialization of the client used to contact Tumblr, I can't really manipulate this right now.

`HttpClientFactory` is a .NET Core class; I know TumblrSharp isn't a .NET Core project and I don't know if there are any plans to make it so, but would it be possible for there to be an option to inject an HttpClient from the calling project into TumblrSharp rather than having initialized inside the library? This way I could manipulate the initialization with the factory class on my own and then pass it in for TumblrSharp to do its thing with.

**Comment by Cataurus** [comment]
I am currently working on support for NetCore 2.2 and higher. It is already in a test phase. Unfortunately I cannot test it in Azure, but only with a local ASP.Net implementation.

**Comment by Cataurus** [comment]
#56 You can find an example of the implementation [here](https://github.com/piedoom/TumblrSharp/tree/master/Examples/ASP.NET%20Core/Simple).

**Comment by blackjackkent** [comment]
No problem on not being able to test in Azure; I got that covered. ;) And awesome that you're doing a migration to .NET Core! Is there any chance that use of the `HttpClientFactory` class could be a part of that rework to help address this issue? It doesn't look like it is currently. (Otherwise, my original request about being able to inject a client from the calling code stands. :) )

**Comment by Cataurus** [comment]
So far it was so, that to create the client this call (over TumblrClientFactory)

```c 
public TClient Create<TClient>(string consumerKey, string consumerSecret, Token oAuthToken = null) where TClient : TumblrClientBase
```
was used.  Within this constructor a classic HtmlClient is used. With NetCore the call is made in this form

```c
public TClient Create<TClient>(IHttpClientFactory httpClientFactory, string consumerKey, string consumerSecret, Token oAuthToken = null) where TClient : TumblrClientBase
```

This uses the ClientFactory.  One thing to note, however, is that the service for the library must be prepared before this call. This is done by executing a static method of the TumblrClientFactory:

```c
 TumblrClientFactory.ConfigureService(IServiceCollection services, string consumerKey, string consumerSecret, Token oAuthToken = null)
```

This call prepares the OAuthMethodHandler, which implements the authorization header for the client to be generated.
In the given [example](https://github.com/piedoom/TumblrSharp/tree/master/Examples/ASP.NET%20Core/Simple), this is realized.

Of course, the old procedure is still available as overload in the conversion for NetCore.

**Comment by Cataurus** [comment]
Update example

- [ASP.Net](https://github.com/piedoom/TumblrSharp/tree/master/Examples/.NET%20Core/ASP.NET)
- [Azure Function](https://github.com/piedoom/TumblrSharp/tree/master/Examples/.NET%20Core/AzureFunction)

**Comment by blackjackkent** [comment]
Okay, sweet, looks good. :) Thank you very much!

**Comment by Cataurus** [comment]
not to thank, if it is feasible, then always gladly
