### ISSUE TITLE
get access token does not work, even if i try to paste the same requestToken which has been fetched on previous step (GetRequestTokenAsync)

### ISSUE THREAD

**Issue by HarutyunGazyan** [piedoom/TumblrSharp#61]
![image](https://user-images.githubusercontent.com/48087308/82655405-2ff3e680-9c33-11ea-8635-eb825efbef3b.png)

**Comment by Cataurus** [comment]
Unfortunately there is not much to see from the code snippet you posted where the error could be. Interesting would be the part how you get the RequestToken and how the verifierCode is produced, which you use in line 74.

To the method the token is passed once and the url is passed once. After the name of your variable you could assume that it is not the url.

```cs
public async Task<Token> GetAccessTokenAsync(Token requestToken, string verifierUrl)
```
You can also have a look at the [example](https://github.com/piedoom/TumblrSharp/tree/master/Examples/.Net%20Framework/Windows/Authenticate), this implements the proceeding from the wiki under windows with using windows forms.

**Comment by HarutyunGazyan** [comment]
Hi, when UI requests tublr URL form back-end at that point request token is fetched and stored as a static variable (just for tests).
After user confirms it from opened window, 
![image](https://user-images.githubusercontent.com/48087308/82796602-d4219b80-9e86-11ea-8858-43f2640409c3.png)
request is redirected to callback, where state, oauth_verifier, oauth_token is extracted from request, and when code tries to fetch GetAccessTokenAsync with stored static request token, app gets an exception which is described above.
My other question is how do I need to store request token for real world application? Obviously it cant be stored as a static variable for asp .net core web api.

**Comment by Cataurus** [comment]
> request is redirected to callback, where state, oauth_verifier, oauth_token is extracted from request, and when code tries to fetch GetAccessTokenAsync with stored static request token, app gets an exception which is described above.

You do not need to do the evaluation, the extraction of state, oauth_verifier and oauth_token, but the method _GetAccessTokenAsync_ itself does that. You pass the entire returned url to the method. This is also the reason for the error.

> My other question is how do I need to store request token for real world application? Obviously it cant be stored as a static variable for asp .net core web api.

Microsoft offers several possibilities for asp.net core projects, a good overview and always with examples can be found [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1).

**Comment by HarutyunGazyan** [comment]
Great, thank you, I've pulled this repo, and seen that I needed to pass entire string, but since it's web api, where app gets params, I've changed that bit of a code.
One more thing, I have also changed the way you are using HttpClient, of course for desktop app it might be ok, but for web app which might be in high load, you can't use HttpClient as you do with using, since using will not help to keep everything disposed, and app might get network exception, please see this https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ .
And also I'm  sure that it' a good idea to use custom message handler just for adding headers to request, so I have also changed that, and replaced that code into simple helper.

**Comment by Cataurus** [comment]
> Great, thank you, I've pulled this repo, and seen that I needed to pass entire string, but since it's web api, where app gets params, I've changed that bit of a code.

By addressing your problem, I have already realized that it is convenient for asp.net applications to provide an overloaded method for GetAccessToken. This overloaded method is already finished and will be provided with the next release.

> One more thing, I have also changed the way you are using HttpClient, of course for desktop app it might be ok, but for web app which might be in high load, you can't use HttpClient as you do with using, since using will not help to keep everything disposed, and app might get network exception, please see this https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ .

Within the TumblrClient only one instance of the HttpClient is used, which is created when creating the TumblrClient. The HttpClient is used repeatedly within the TumblrClient. The described problem should not occur with it. So to speak exactly this is implemented. When the TumblrClient is destroyed, this HttpClient is released.

part of TumblrClientBase.cs
```cs
	public class TumblrClientBase : IDisposable
	{
		private readonly object disposeLock = new object();
		private bool disposed;

		private readonly HttpClient client;
		
		public TumblrClientBase(IHmacSha1HashProvider hashProvider, string consumerKey, string consumerSecret, Token oAuthToken = null)
		{
			if (consumerKey == null)
				throw new ArgumentNullException(nameof(consumerKey));

			if (consumerKey.Length == 0)
				throw new ArgumentException("Consumer key cannot be empty.", nameof(consumerKey));

			if (consumerSecret == null)
				throw new ArgumentNullException(nameof(consumerSecret));

			if (consumerSecret.Length == 0)
				throw new ArgumentException("Consumer secret cannot be empty.", nameof(consumerSecret));

			this.oAuthToken = oAuthToken;
			this.client = new HttpClient(new OAuthMessageHandler(hashProvider, consumerKey, consumerSecret, oAuthToken));
		}

		public void Dispose()
		{
			if (!disposed)
			{
				lock (disposeLock)
				{
					if (!disposed)
					{
						disposed = true;
						client.Dispose();
						Dispose(true);
						GC.SuppressFinalize(this);
					}
				}
			}
		}
```


> And also I'm sure that it' a good idea to use custom message handler just for adding headers to request, so I have also changed that, and replaced that code into simple helper.

I'd like to see your solution.
