### ISSUE TITLE
GetFollowersAsync - Question

### ISSUE THREAD

**Issue by elmagekmosaad** [piedoom/TumblrSharp#64]
hi
can i GetFollowers for any user or for my account only?

**Comment by Cataurus** [comment]
retrieves a blog's followers. see also [doc for GetFollowersAsync](https://cataurus.github.io/TumblrSharp/api/DontPanic.TumblrSharp.Client.TumblrClient.GetFollowersAsync.html)

**Comment by elmagekmosaad** [comment]
I do this but return blog not found and blog work

في الاثنين، ٢٩ يونيو، ٢٠٢٠ ١:٥٨ م Ulf Prill <notifications@github.com> كتب:

**Comment by Cataurus** [comment]
The restrictions result from the API of Tumblr. For example, the [Tumblr documentation](https://www.tumblr.com/docs/en/api/v2#userfollowing--retrieve-the-blogs-a-user-is-following) says the following about the method: **/user/following** -

>  Use this method to retrieve the blogs followed by the user _whose OAuth credentials_ are submitted with the request

Unfortunately, Tumblr's documentation on the information is not very consistent. This is probably true for [GetFollowersAsync](https://www.tumblr.com/docs/en/api/v2#followers--retrieve-a-blogs-followers), even if it is not explicitly stated there. It is probably only valid for the authorized user.
