### ISSUE TITLE
DontPanic.TumblrSharp.OAuth.OAuthException: 'GetRequestTokenAsync failed. Status Code: Unauthorized, Message: Unauthorized'

### ISSUE THREAD

**Issue by elmagekmosaad** [piedoom/TumblrSharp#67]
DontPanic.TumblrSharp.OAuth.OAuthException: 'GetRequestTokenAsync failed. Status Code: Unauthorized, Message: Unauthorized'

**Comment by Cataurus** [comment]
Unfortunately, this is a bit too little information to analyze the problem. I tried again our [example ](https://github.com/piedoom/TumblrSharp/tree/master/Examples/.Net%20Framework/Windows/Authenticate) , this one works.

**Comment by elmagekmosaad** [comment]
> 
> 
> Unfortunately, this is a bit too little information to analyze the problem. I tried again our [example ](https://github.com/piedoom/TumblrSharp/tree/master/Examples/.Net%20Framework/Windows/Authenticate) , this one works.

I already tried it and tried other examples but it shows the same error
I even created a new app but to no avail

**Comment by Cataurus** [comment]
There would then be a presumption that there is a problem with the consumer token.
Try the official [API console](https://api.tumblr.com/console/calls/user/info) from Tumblr to test your consumer key and secret.
Let me know if it worked with them.

**Comment by elmagekmosaad** [comment]
> 
> 
> There would then be a presumption that there is a problem with the consumer token.
> Try the official [API console](https://api.tumblr.com/console/calls/user/info) from Tumblr to test your consumer key and secret.
> Let me know if it worked with them.

yes it's worked in api console
![image](https://user-images.githubusercontent.com/19142989/128523469-e2f410b8-2e44-4b53-b53b-f5e8cda4bb9f.png)

**Comment by elmagekmosaad** [comment]
but still error DontPanic.TumblrSharp.OAuth.OAuthException: 'GetRequestTokenAsync failed. Status Code: Unauthorized, Message: Unauthorized'
in my program and exambles
![image](https://user-images.githubusercontent.com/19142989/128523974-dc56d456-66af-48c0-a1d2-22feefe9908d.png)

**Comment by Cataurus** [comment]
I have never tested our library under Visual Basic. My knowledge of Visual Basic is rather limited.
To follow your example, I would like to know which version of the .Net Framework your program uses?
Which Visual Studio version you are using?
Maybe you can also just send me your test project before I have to rebuild it. That would make it a lot easier.

**Comment by elmagekmosaad** [comment]
> 
> 
> I have never tested our library under Visual Basic. My knowledge of Visual Basic is rather limited.
> To follow your example, I would like to know which version of the .Net Framework your program uses?
> Which Visual Studio version you are using?
> Maybe you can also just send me your test project before I have to rebuild it. That would make it a lot easier.

can you chat with me on facebook ?
https://www.facebook.com/elmagekmosaad
